### ISSUE TITLE
Groceries that take SNAP

### ISSUE THREAD

**Issue by bondah** [maptimeLA/food_bank_data_bank#1]
USDA web map: http://www.fns.usda.gov/snap/retailerlocator

Figure out how to scrape the dataset.

**Comment by bondah** [comment]
Found the download! Added the csv to the repository.

**Comment by matikin9** [comment]
Downloadable CSV by state at the bottom:

![image](https://cloud.githubusercontent.com/assets/1873072/9128234/0c312cda-3c7a-11e5-8dc9-dbb10c21fbea.png)
