### ISSUE TITLE
SNAP Benefit Usage.

### ISSUE THREAD

**Issue by JRHutson** [maptimeLA/food_bank_data_bank#11]
Need to get info on population using Federal SNAP Benefits. Should be able to download from the Census Bureau. 2010 Census data should be available at the Block level, but is 5yrs old. American Community Survey should have data from 2013, but will be broken down by Block Group.

**Comment by JRHutson** [comment]
Could be included in this dataset that Andy suggested. http://thedataweb.rm.census.gov/ftp/sipp_ftp.html

**Comment by MappingMary** [comment]
so what does this mean ?

**Comment by JRHutson** [comment]
Uploaded Data on SNAP benefit receipt to repo.
