### ISSUE TITLE
Trying to calculate population density.

### ISSUE THREAD

**Issue by JRHutson** [maptimeLA/food_bank_data_bank#13]
Anyone have experience doing the area calculation in Q-Gis? I'm trying to add Population Density to the Census Block Group Shapefile and none of the data is making sense. According to what I can find online, the $area function should give you the area of the polygon in whatever units correspond to the layer's projection. The shape file is projected in feet, so I assume that means the output would be Sq.Ft. 

Trying to use the field calculator just isn't even responding for me. (I enabled editing, got conformation of a valid function, clicked ok. The designated field just doesn't update. No idea why not...) Tried Exporting to a new shape file with geometry columns added. (Under the vector menu) Outputs a new shape file successfully, but the data makes no sense. A huge block in the high desert has an area of 0.07. What the hell are the units????? That's not even Square Miles!!!!

Any help making sense of this mess would be appreciated. Hope you're all staying cool this weekend.

**Comment by bondah** [comment]
The shapefile had the projection defined as CA State Plane Zone 5 feet, but was actually still in WGS84 Lat/Long. I set the projection back to WGS84 and then re-projected to CA State Plane Zone 5 feet. Should be good now. Calcs are run and look reasonable. See pull request.
