### ISSUE TITLE
Organizer / Project Lead checklist for Thurs. 9/3 Food Data Night

### ISSUE THREAD

**Issue by machikoyasuda** [maptimeLA/food_bank_data_bank#24]
**Project Lead**:
@JRHutson 

**Organizers**:
@cityhubla 
@csterling 
@machikoyasuda

**Mentors**:
@patriciarealini - GitHub / Front-end / JavaScript

**Small Group Leaders**:
- data processing/analyzing - @csterling 
- github office hours / data visualizing - @machikoyasuda
## Possible small groups:
- `OpenStreetMap` Office Hours: training + lead
- GitHub Office Hours: One-on-one training to clone, pull, branch, make commits, push, pull request, and then pull again.
- HTML/CSS/JS for website
## Food & Amenities

[ ] Ordering food
[ ] Assign food pick-up
[ ] Set up food table, plates/cups/napkins
## Tips for organizers:
- **Google Docs & Spreadsheets**: Set everything to `Publish to Web` so anyone can view, but make sure everyone needs permission to edit. Link all relevant docs in the `README.md`
- **Deploy** something to the site page ahead of time for everyone to see.
- **In case the WiFi goes down**: Download as much files, application installers, onto computer and/or USB stick as possible!  💾 💾 💾
## Tips for project leads:
1. Assign someone to be the Issue Tracker Leader for the brainstorming/issue session. They will create issues for each thing as they get discussed. Assign someone to be the Wireframer. 
2. Brainstorm and wireframe together on a white board. Write all the ideas raised down. (Which will then be created as Issues by the Issue Tracker Leader. Wireframer can draw it out on whiteboard.)
3. Ask people what they want to work on, what kind of apps they want to use, and divvy up tasks by pairs
4. Assign as GitHub issues to these pairs.

**Comment by JRHutson** [comment]
I should be getting a list of questions from Andy on Monday. We can use that as a guide for how many groups we expect to divide people into. It should be 2-3 questions each department at the Food Bank would want to answer with the data.

**Comment by chanbot5000** [comment]
I can lead data processing/analyzing

**Comment by machikoyasuda** [comment]
@patriciarealini @LearningNerd - can you come to the data night? would love to have y'all there + mentor/lead project sessions.

**Comment by JRHutson** [comment]
Going to start adding the Questions from Andy to the Repo. The night of, I'm planning to float. Appreciate the organization support.

**Comment by patriciarealini** [comment]
@machikoyasuda i'll be there!

**Comment by JRHutson** [comment]
I've gotten pretty good with the Data Ferret utility. I can also be on-call for any critical requests for additional datasets.

**Comment by machikoyasuda** [comment]
![image](https://cloud.githubusercontent.com/assets/3673236/9613018/ce7a78f0-509d-11e5-9957-38bf1ef53cbb.png)

**Comment by machikoyasuda** [comment]
![ferret](https://cloud.githubusercontent.com/assets/3673236/9613035/e75b04c0-509d-11e5-8ece-45ddfc4c84c2.gif)

**Comment by JRHutson** [comment]
@machikoyasuda That's pretty much the process. You have to earn the Ferret's respect before it will give you your dataset.
