### ISSUE TITLE
Farmer's Markets that take EBT/CalFresh

### ISSUE THREAD

**Issue by matikin9** [maptimeLA/food_bank_data_bank#3]
In map form, for all of California.
http://ecologycenter.org/fmfinder/

I pulled the raw json, we just need to filter for LA County.

**Comment by JRHutson** [comment]
Nina, are you going to take care of filtering the data? Feel free to add the json to the repo if you don't have time and someone else can pick it up.

**Comment by matikin9** [comment]
Uploaded the original JSON dataset (all of CA) as well as a JSON file containing the data for just LA County.  We still need a shapefile.

**Comment by JRHutson** [comment]
It is in JSON form rather than GeoJSON. The Latitude and Longitude are stored in two of the fields so it should be easy to Geocode. Then we can add GeoJSON and Shapefile.

**Comment by matikin9** [comment]
I was able to convert it to CSV format so I've uploaded that file as well.

**Comment by JRHutson** [comment]
Geocoded locations from the CSV and uploaded both GeoJSON and Shapefile.
