### ISSUE TITLE
Geocode Food Markets

### ISSUE THREAD

**Issue by JRHutson** [maptimeLA/food_bank_data_bank#42]
Geocode CSV of Food Markets in Food Sources Folder. Upload Shapefile and GeoJSON.

**Comment by chanbot5000** [comment]
The CSV in this folder is for Market Violations. Is that correct? @JRHutson

**Comment by JRHutson** [comment]
That's correct but I think you already figured that out.

**Comment by johnhickok** [comment]
Finally added a field to health districts. Github command line works.

_Trying paperless..._

John Hickok, PLS, GISP
Los Angeles County, Department of Public Works
Contact: jhickok@dpw.lacounty.gov, 626-824-8870

**Comment by johnhickok** [comment]
PS - next meeting on Thursday Night isat ELACC, 530 South Boyle Ave - got
tips on where to park over there?

_Trying paperless..._

John Hickok, PLS, GISP
Los Angeles County, Department of Public Works
Contact: jhickok@dpw.lacounty.gov, 626-824-8870

**Comment by JRHutson** [comment]
@johnhickok Were you able to make a commit? I'm not seeing one on this end.

**Comment by machikoyasuda** [comment]
@cityhubla what is the parking like around ELACC? 

@johnhickok there should be street parking along Boyle Av, next to Hollenbeck Park:

![screenshot 2015-08-31 11 10 52](https://cloud.githubusercontent.com/assets/3673236/9586342/17a432e6-4fd1-11e5-9729-0d139cfe2c52.png)
![screenshot 2015-08-31 11 10 57](https://cloud.githubusercontent.com/assets/3673236/9586343/17aadc90-4fd1-11e5-910d-c92d33464730.png)

**Comment by cityhubla** [comment]
@machikoyasuda @johnhickok, There is plenty of street parking, you should be able to find a spot close by.

**Comment by johnhickok** [comment]
Got no error message.

**Comment by JRHutson** [comment]
@machikoyasuda GitHub isn't showing a commit by John. He's using command line. Could you help sort out what the issue it?
