### ISSUE TITLE
Map idea: Farmers Markets that accept WIC / EBT

### ISSUE THREAD

**Issue by machikoyasuda** [maptimeLA/food_bank_data_bank#59]
## Your challenge:
1. Map all the Farmers Markets. Deploy this map. Data: 
   https://github.com/maptimeLA/food_bank_data_bank/tree/master/datasets/FoodSources/CA-WIC-Farmer-Markets https://github.com/maptimeLA/food_bank_data_bank/tree/master/datasets/FoodSources/CalFreshFarmersMarkets
2. Categorize Farmers Markets by WIC / EBT - accepting or not. 
3. Draw City Council Boundaries. 
4.  :hash: **Analysis Challenge** :hash:  Calculate and display what percentage of Farmers Markets in each CouncIl District accept WIC / EBT.
5. When you deploy the map, remember to add these :pencil2: **Maptime Map essentials** :pencil2: The `source` of the data, the `date` of the data, the `link` to the data, and a `Google Form` to let us know if the data needs to be updated, and what to update.
## Bonus :star:
- Add a layer of all retailers that accept WIC / EBT / SNAP. Data here: https://github.com/maptimeLA/food_bank_data_bank/tree/master/datasets/FoodSources/LACountyWICRetailers https://github.com/maptimeLA/food_bank_data_bank/tree/master/datasets/FoodSources/SNAP%20Locations
## Quadruple Bonus :star: :star: :star: :star:
- Categorize the farmers markets by when they are open: Open on Weekends, Weekdays, Daytime, Nights.
- Categorize the other retailers by when they are open: 24 Hours, Regular Hours, Nights/Weekends
## SRSLY?
- Map the major public transit lines.
- Translate the map into various languages. As many languages as possible.
- Add lots of emojis :apple: :green_apple: :egg:

**Comment by songcy** [comment]
I can take this one!

**Comment by machikoyasuda** [comment]
Awesome @songcy  - I invited you to the MaptimeLA GitHub group. I believe if you accept that email confirmation, I can assign you to this issue :) :apple:

**Comment by JRHutson** [comment]
@songcy We're doing a project night next week for Maptime. Would you be interested in having some collaborators and turning this into a project for that night or were you looking to tackle it on your own? I'm finishing up a project that I wanted to tackle myself as a learning experience, so I understand either way.
   Regan

**Comment by songcy** [comment]
@JRHutson Hey, I'm sorry. I didn't anticipate how swamped I'd be with exams and assignments this past week. I was planning on going to the meeting tonight, so I should be there a bit late. Go ahead start on this too! I don't mind at all. If anything I'm sure I could learn something from you.

**Comment by JRHutson** [comment]
Tonight we'll be focusing on retail locations that accept SNAP, so the Farmers Markets will be an additional resource to consider in the future. See you there tonight.
