### ISSUE TITLE
Unable to Join. 

### ISSUE THREAD

**Issue by JRHutson** [maptimeLA/food_bank_data_bank#8]
Was unable to join Census Block Group population totals to Census Block Group Shapefile. Find source of error and resolve.

**Comment by bondah** [comment]
I was able to join, but you have to move the csv file to another folder. ArcGIS can't handle the dashes in the github repo name for old school formats like csv. Maybe we should change the name to underscores?

**Comment by machikoyasuda** [comment]
how to rename a repo:

https://help.github.com/articles/renaming-a-repository/

![screenshot 2015-08-13 18 08 50](https://cloud.githubusercontent.com/assets/3673236/9265315/5f2867d4-41e6-11e5-8ca6-8ca5e9ab9e7d.png)

**Comment by JRHutson** [comment]
Bond, Are you getting data from the join? I'm working in Q-Gis and have been able to join the two all along. I just get null values for the data that should be coming from the CSV. 
![image](https://cloud.githubusercontent.com/assets/10876900/9266473/5496aa96-41f6-11e5-9502-6daf952609a8.png)

**Comment by JRHutson** [comment]
Should have given a better explanation of the problem from the beginning.

**Comment by MappingMary** [comment]
This might sound stupid, but maybe there isn't a population in the census block that is giving you nulls.. I think that is Los Angeles National Forest ? thinking out loud..

**Comment by bondah** [comment]
Are you using geo.id2? I just tried the join in QGIS and it shows the data after join. 
![image](https://cloud.githubusercontent.com/assets/8827412/9273720/ba14b8e6-4254-11e5-9008-1d72320d31a6.png)

**Comment by JRHutson** [comment]
That's what I was doing. And it definitely is more than isolated block groups with null values. Strangely, if I uncheck the option to cache the join layer in virtual memory the join works normally, but the application gets unstable.
<img width="905" alt="screen shot 2015-08-14 at 6 47 30 am" src="https://cloud.githubusercontent.com/assets/10876900/9275295/ef6743e6-4250-11e5-9720-aa88a42bd98f.png">
<img width="839" alt="screen shot 2015-08-14 at 6 48 04 am" src="https://cloud.githubusercontent.com/assets/10876900/9275296/ef692288-4250-11e5-9092-b06cb694b3ae.png">

**Comment by bondah** [comment]
I see you are joining on id2. Did you delete the header row? If you delete the header row and read in the csv, id2 comes in as type Double and then you can't join to the String geoid field in the shapefile. If you read it in direct from the GitHub folder and leave the second row of text, it comes in as a string. Alternatively, you can create a geoid_num field as type decimal (length 12) and copy over the values from id2 then join on that.

**Comment by JRHutson** [comment]
It's probably a field type issue. I'll try creating a new field as you suggested. Updating to the new Q-GIS version as well to avoid any issue from that.

**Comment by JRHutson** [comment]
I finally got it to work after copying the column and pasting as formula result into a new column.

**Comment by MappingMary** [comment]
Did you figure it out? curious did you first modify the fields you are trying to join because they are different so your right you would not get a descent join. create a new field for both attribute tables and you are going to match on the block level identification number  ..
![join1](https://cloud.githubusercontent.com/assets/11170368/9282970/e5a1d7ca-4284-11e5-8b46-eb957ecac173.JPG)

**Comment by MappingMary** [comment]
i will have more time after Saturday, sorry. Saturday is my last day of school :)

**Comment by JRHutson** [comment]
For some reason Q-Gis wasn't letting me edit the CSV so I had to edit it in Numbers. (Don't want to pay for Excel ) To get the field type to match I ended up having to pass it through two new fields. The first had a formula to add the leading "0" that was being removed when it was treated as a number. Once that was added, I copied and pasted the column into another column using "Paste Result" so that it was treated as a string rather than a number.

**Comment by MappingMary** [comment]
I C.. my experience with ARCMAP in regards to excel, typical csv is not used do to formatting issues (dates e.g) when it is being imported to be a db table (idk y and i haven't looked into it) . i usually save it as xls and i use the toolbox to do my conversion to excel to db table into the geocan.  I dont know Q-GIS and i would have no idea if the field calculator is the same set up as it is in ARCMAP, if it is you can enter an expression either VB or Python to strip the corresponding numbers that are associated to identify the block group, in most cases using data from census it is the last 7 numbers,  sorry i cant be more help.. if no one else has volunteered i dont mind doing the geocoding. i can have it done by Sunday if necessary. you have my contact info.. and im still playing with git so i can upload or "push" commit" or whatever and now i have shell so hopefully i can be more of a active team member. thank you !  c u online :)
